.TH "md_CONTRIBUTING" 3 "Sun Mar 19 2023" "Version v1.1.1" "slou" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_CONTRIBUTING \- CONTRIBUTING 
.PP

.SH "Contributing to slou"
.PP
First off, thanks for taking the time to contribute! ❤️
.PP
All types of contributions are encouraged and valued\&. See the \fBTable of Contents\fP for different ways to help and details about how this project handles them\&. Please make sure to read the relevant section before making your contribution\&. It will make it a lot easier for us maintainers and smooth out the experience for all involved\&. The community looks forward to your contributions\&. 🎉
.PP
.RS 4
And if you like the project, but just don't have time to contribute, that's fine\&. There are other easy ways to support the project and show your appreciation, which we would also be very happy about:
.IP "\(bu" 2
Star the project
.IP "\(bu" 2
Tweet about it
.IP "\(bu" 2
Refer this project in your project's readme
.IP "\(bu" 2
Mention the project at local meetups and tell your friends/colleagues 
.PP
.RE
.PP
.SS "Table of Contents"
.IP "\(bu" 2
\fBCode of Conduct\fP
.IP "\(bu" 2
\fBI Have a Question\fP
.IP "\(bu" 2
\fBI Want To Contribute\fP
.IP "  \(bu" 4
\fBReporting Bugs\fP
.IP "  \(bu" 4
\fBSuggesting Enhancements\fP
.IP "  \(bu" 4
\fBYour First Code Contribution\fP
.IP "  \(bu" 4
\fBImproving The Documentation\fP
.PP

.IP "\(bu" 2
\fBStyleguides\fP
.IP "  \(bu" 4
\fBCommit Messages\fP
.PP

.IP "\(bu" 2
\fBJoin The Project Team\fP
.PP
.SS "Code of Conduct"
This project and everyone participating in it is governed by the \fCslou Code of Conduct\fP\&. By participating, you are expected to uphold this code\&. Please report unacceptable behavior to jakubskowron676@gmail.com\&.
.SS "I Have a Question"
.RS 4
If you want to ask a question, we assume that you have read the available \fCDocumentation\fP\&. 
.RE
.PP
Before you ask a question, it is best to search for existing \fCIssues\fP that might help you\&. In case you have found a suitable issue and still need clarification, you can write your question in this issue\&. It is also advisable to search the internet for answers first\&.
.PP
If you then still feel the need to ask a question and need clarification, we recommend the following:
.PP
.IP "\(bu" 2
Open an \fCIssue\fP\&.
.IP "\(bu" 2
Provide as much context as you can about what you're running into\&.
.IP "\(bu" 2
Provide project and platform versions (nodejs, npm, etc), depending on what seems relevant\&.
.PP
.PP
We will then take care of the issue as soon as possible\&.
.SS "I Want To Contribute"
.RS 4
### Legal Notice When contributing to this project, you must agree that you have authored 100% of the content, that you have the necessary rights to the content and that the content you contribute may be provided under the project license\&. 
.RE
.PP
.SS "Reporting Bugs"
.SS "Before Submitting a Bug Report"
A good bug report shouldn't leave others needing to chase you up for more information\&. Therefore, we ask you to investigate carefully, collect information and describe the issue in detail in your report\&. Please complete the following steps in advance to help us fix any potential bug as fast as possible\&.
.PP
.IP "\(bu" 2
Make sure that you are using the latest version\&.
.IP "\(bu" 2
Determine if your bug is really a bug and not an error on your side e\&.g\&. using incompatible environment components/versions (Make sure that you have read the \fCdocumentation\fP\&. If you are looking for support, you might want to check \fBthis section\fP)\&.
.IP "\(bu" 2
To see if other users have experienced (and potentially already solved) the same issue you are having, check if there is not already a bug report existing for your bug or error in the \fCbug tracker\fP\&.
.IP "\(bu" 2
Also make sure to search the internet (including Stack Overflow) to see if users outside of the GitHub community have discussed the issue\&.
.IP "\(bu" 2
Collect information about the bug:
.IP "  \(bu" 4
Stack trace (Traceback)
.IP "  \(bu" 4
OS, Platform and Version (Windows, Linux, macOS, x86, ARM)
.IP "  \(bu" 4
Version of the interpreter, compiler, SDK, runtime environment, package manager, depending on what seems relevant\&.
.IP "  \(bu" 4
Possibly your input and the output
.IP "  \(bu" 4
Can you reliably reproduce the issue? And can you also reproduce it with older versions?
.PP

.PP
.SS "How Do I Submit a Good Bug Report?"
.RS 4
You must never report security related issues, vulnerabilities or bugs including sensitive information to the issue tracker, or elsewhere in public\&. Instead sensitive bugs must be sent by email to jakubskowron676@gmail.com\&. 
.RE
.PP
.PP
We use GitHub issues to track bugs and errors\&. If you run into an issue with the project:
.PP
.IP "\(bu" 2
Open an \fCIssue\fP\&. (Since we can't be sure at this point whether it is a bug or not, we ask you not to talk about a bug yet and not to label the issue\&.)
.IP "\(bu" 2
Explain the behavior you would expect and the actual behavior\&.
.IP "\(bu" 2
Please provide as much context as possible and describe the \fIreproduction steps\fP that someone else can follow to recreate the issue on their own\&. This usually includes your code\&. For good bug reports you should isolate the problem and create a reduced test case\&.
.IP "\(bu" 2
Provide the information you collected in the previous section\&.
.PP
.PP
Once it's filed:
.PP
.IP "\(bu" 2
The project team will label the issue accordingly\&.
.IP "\(bu" 2
A team member will try to reproduce the issue with your provided steps\&. If there are no reproduction steps or no obvious way to reproduce the issue, the team will ask you for those steps and mark the issue as \fCneeds-repro\fP\&. Bugs with the \fCneeds-repro\fP tag will not be addressed until they are reproduced\&.
.IP "\(bu" 2
If the team is able to reproduce the issue, it will be marked \fCneeds-fix\fP, as well as possibly other tags (such as \fCcritical\fP), and the issue will be left to be \fBimplemented by someone\fP\&.
.PP
.SS "Suggesting Enhancements"
This section guides you through submitting an enhancement suggestion for slou, \fBincluding completely new features and minor improvements to existing functionality\fP\&. Following these guidelines will help maintainers and the community to understand your suggestion and find related suggestions\&.
.SS "Before Submitting an Enhancement"
.IP "\(bu" 2
Make sure that you are using the latest version\&.
.IP "\(bu" 2
Read the \fCdocumentation\fP carefully and find out if the functionality is already covered, maybe by an individual configuration\&.
.IP "\(bu" 2
Perform a \fCsearch\fP to see if the enhancement has already been suggested\&. If it has, add a comment to the existing issue instead of opening a new one\&.
.IP "\(bu" 2
Find out whether your idea fits with the scope and aims of the project\&. It's up to you to make a strong case to convince the project's developers of the merits of this feature\&. Keep in mind that we want features that will be useful to the majority of our users and not just a small subset\&. If you're just targeting a minority of users, consider writing an add-on/plugin library\&.
.PP
.SS "How Do I Submit a Good Enhancement Suggestion?"
Enhancement suggestions are tracked as \fCGitHub issues\fP\&.
.PP
.IP "\(bu" 2
Use a \fBclear and descriptive title\fP for the issue to identify the suggestion\&.
.IP "\(bu" 2
Provide a \fBstep-by-step description of the suggested enhancement\fP in as many details as possible\&.
.IP "\(bu" 2
\fBDescribe the current behavior\fP and \fBexplain which behavior you expected to see instead\fP and why\&. At this point you can also tell which alternatives do not work for you\&.
.IP "\(bu" 2
You may want to \fBinclude screenshots and animated GIFs\fP which help you demonstrate the steps or point out the part which the suggestion is related to\&. You can use \fCthis tool\fP to record GIFs on macOS and Windows, and \fCthis tool\fP or \fCthis tool\fP on Linux\&.
.IP "\(bu" 2
\fBExplain why this enhancement would be useful\fP to most slou users\&. You may also want to point out the other projects that solved it better and which could serve as inspiration\&.
.PP
.SS "Your First Code Contribution"
This section will describe how to setup a development environment for working on slou\&.
.SS "Build system"
slou uses \fCMeson\fP and \fCNinja\fP to build the project so make sure you have that\&. You can find instructions on how to install it \fChere\fP\&.
.SS "Code editor"
You can use any code editor for development, there aren't any requirements\&.
.SS "Building"
If you use Linux for compilation please compile for Windows as well\&. In the root directory there's a \fCwin64\&.crossfile\fP that you can use to compile for both Linux and Windows\&.
.PP
To compile execute these commands:
.PP
.PP
.nf
$ mkdir build/
$ cd build/
$ meson setup \-\-prefix /usr build\-linux\-x86_64/ \&.\&./
$ meson setup \-\-cross\-file \&.\&./win64\&.crossfile build\-windows\-x86_64/ \&.\&./
.fi
.PP
.PP
And then to compile, while in the root directory:
.PP
.PP
.nf
$ meson compile \-C build/build\-linux\-x86_64/
$ meson compile \-C build/build\-windows\-x86_64/
.fi
.PP
.PP
If you use Windows, for the time being you can only compile for Windows, which is good because the lead developer does not have a Windows computer and will not for some time\&. :)
.SS "Improving The Documentation"
As slou uses \fCDoxygen\fP for documentation, you really don't need to do much except for installing it and documenting the code properly\&.
.SS "Styleguides"
.SS "Commit Messages"
When fixing an issue please make sure to include the issue number in your commit message\&. We don't require anymore than that\&.
.SS "Attribution"
This guide is based on the \fBcontributing-gen\fP\&. \fCMake your own\fP! 
