.TH "md_CHANGELOG" 3 "Wed Mar 22 2023" "Version v1.2.0" "slou" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_CHANGELOG \- Release Notes 
.PP
These are the relase notes for \fCslou\fP\&.
.SH "v1\&.2\&.0 | 21, mar\&. 2023"
.PP
\fBAdded\fP
.IP "\(bu" 2
Named Parameter Idioms instead of positional arguments in the constructor (\fCprojectName\fP is an exception)
.IP "\(bu" 2
New log format variable, \fCmoduleName\fP which is the module name (e\&.g\&. class name) \fBChanged\fP
.IP "\(bu" 2
Changeable variables initialized in the constructor are now private immutable variables only used for initialization\&. To change those variables, you'll have to use the NPIs
.PP
.SH "v1\&.1\&.1 | 19, mar\&. 2023"
.PP
\fBChanged\fP
.IP "\(bu" 2
Changed variables \fCshouldLogToFile\fP and \fCshouldLogToScreen\fP to \fClogToFile\fP and \fClogToScreen\fP
.PP
.PP
\fBAdded\fP
.IP "\(bu" 2
\fCcolorTerminalOutput\fP to check if the user wants to color the terminal output
.IP "\(bu" 2
\fCUSAGE\&.md\fP file as smaller documentation explaining ways of configuration for The Logger
.PP
.SH "v1\&.1\&.0 | 17, mar\&. 2023"
.PP
\fBAdded\fP
.IP "\(bu" 2
Custom formatting similar to the Python \fClogging\fP library
.PP
.SH "v1\&.0\&.1 | 11, mar\&. 2023"
.PP
\fBChanged\fP
.IP "\(bu" 2
Changed \fCCurrentDateAndTime()\fP function to make it more cross-platform ('cause I've learned from my friend that \fClocaltime\fP is not supported on Windows)
.PP
.SH "v1\&.0\&.0 | 11, mar\&. 2023"
.PP
.IP "\(bu" 2
Initial release 
.PP

