.TH "md_SECURITY" 3 "Sun Mar 12 2023" "Version v1.0.0" "slou" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_SECURITY \- Security Policy 
.PP

.SH "Supported Versions"
.PP
As slou isn't really a library or project that can have security issues, any and all versions of slou are supported\&.
.PP
But please use the latest version to ensure you have new features as they roll out\&. :)
.SH "Reporting a Vulnerability"
.PP
To report a vulnerabity please refer to \fCCONTRIBUTING\&.md\fP\&. 
