.TH "src/slou.hpp" 3 "Fri Mar 17 2023" "Version v1.1.0" "slou" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/slou.hpp \- The most important file in this library\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <fstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBslou::Logger\fP"
.br
.RI "Class creates the logger that logs everything to the screen and/or file\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBslou\fP"
.br
.RI "'slou' namespace\&. "
.in -1c
.SH "Detailed Description"
.PP 
The most important file in this library\&. 


.PP
Definition in file \fBslou\&.hpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define SLOU_PUBLIC"

.PP
Definition at line \fB20\fP of file \fBslou\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for slou from the source code\&.
