.TH "slou" 3 "Sat Mar 11 2023" "Version v1.0.0" "slou" \" -*- nroff -*-
.ad l
.nh
.SH NAME
slou \- 'slou' namespace\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLogger\fP"
.br
.RI "Main class creates the logger that logs everything to the screen and/or file\&. "
.in -1c
.SH "Detailed Description"
.PP 
'slou' namespace\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for slou from the source code\&.
